[package]
name = "size"
version = "0.1.2"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>", "NeoSmart Technologies"]
description = "Units and formatting for file sizes in base2 and base10"
homepage = "https://github.com/neosmart/prettysize-rs"
repository = "https://github.com/neosmart/prettysize-rs"
readme = "README.md"
keywords = ["bytes", "prettysize", "size", "units", "formatting"]
categories = ["value-formatting"]
license = "MIT"
edition = "2018"

[dependencies]
num-traits = { version = "0.2", default-features = false }

[features]
default = [ "std" ]
std = []
